name: Update PROD2 Weekly

on:
  workflow_dispatch:

  schedule:

    # Tous les jours à 01h00 (heure française d'été)
    - cron: '0 23 * * *'

    # Jeudi toutes les 2 minutes de 19h00 à 22h58
    - cron: '*/2 17-21 * * 4'

    # Vendredi toutes les 2 minutes de 19h00 à 22h58
    - cron: '*/2 17-21 * * 5'

jobs:

  update:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install requests beautifulsoup4 firebase-admin

      - run: python update_prod2_weekly.py
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
