name: Update PROD2 Live

on:
  workflow_dispatch:

  schedule:
    - cron: '*/10 17-23 * * 4'
    - cron: '*/10 17-23 * * 5'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Installation des dépendances classiques
      - run: pip install requests beautifulsoup4 firebase-admin

      # Installation de Playwright (lib Python)
      - name: Install Playwright
        run: pip install playwright

      # Installation des navigateurs Playwright
      - name: Install Playwright browsers
        run: playwright install --with-deps

      # Exécution de ton script
      - run: python update_prod2_live.py
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
