name: Update TOP14 Weekly

on:
  workflow_dispatch:

  schedule:

    # Tous les jours à 01h00 (heure française d'été)
    - cron: '0 23 * * *'

    # Samedi toutes les 2 minutes de 15h00 à 22h58
    - cron: '*/2 12-21 * * 6'

    # Dimanche toutes les 2 minutes de 21h00 à 22h58
    - cron: '*/2 19-21 * * 0'

jobs:

  update:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install requests beautifulsoup4 firebase-admin

      - run: python update_top14_weekly.py
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
